"""Regenerate the self-contained Studio installer from the checked-in Luau sources."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def literal(source: str) -> str:
    equals = "="
    while "]" + equals + "]" in source:
        equals += "="
    return "[" + equals + "[\n" + source + "]" + equals + "]"


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8-sig")


output = ['''-- GENERATED by tools/GenerateInstaller.py. Run in Studio's command bar in EDIT mode.
-- Installs Dream Valley, game scripts, reusable assets, and local ambience.
local RS=game:GetService("ReplicatedStorage")
local package=RS:FindFirstChild("PaperFlight") or Instance.new("Folder")
package.Name="PaperFlight"; package.Parent=RS
local function write(parent,name,class,source)
 local instance=parent:FindFirstChild(name) or Instance.new(class)
 instance.Name=name; instance.Source=source; instance.Parent=parent
end
''']
for parent, name, cls, path in [
    ("package", "Config", "ModuleScript", "src/shared/Config.luau"),
    ("package", "Flight", "ModuleScript", "src/shared/Flight.luau"),
    ('game:GetService("ServerScriptService")', "PaperFlightServer", "Script", "src/server/RaceServer.server.luau"),
    ("game.StarterPlayer.StarterPlayerScripts", "PaperFlightClient", "LocalScript", "src/client/FlightClient.client.luau"),
    ("game.StarterPlayer.StarterPlayerScripts", "PaperFlightAmbience", "LocalScript", "src/client/WorldAmbience.client.luau"),
]:
    output.append(f'write({parent},"{name}","{cls}",{literal(read(path))})\n')
output.append('local remote=package:FindFirstChild("RaceEvent") or Instance.new("RemoteEvent"); remote.Name="RaceEvent"; remote.Parent=package\n')
output.append("local function buildWorld()\n" + read("tools/BuildDreamWorld.luau") + "\nend\nprint(buildWorld())\n")
(ROOT / "tools/InstallDreamValley.luau").write_text("".join(output), encoding="utf-8")
models_only = '''-- GENERATED: run in Studio EDIT mode to install scenery and ambience only.
-- Requires the existing ReplicatedStorage.PaperFlight.Config module.
local parent=game.StarterPlayer.StarterPlayerScripts
local ambience=parent:FindFirstChild("PaperFlightAmbience") or Instance.new("LocalScript")
ambience.Name="PaperFlightAmbience"
'''
models_only += "ambience.Source=" + literal(read("src/client/WorldAmbience.client.luau")) + "\nambience.Parent=parent\n"
models_only += read("tools/BuildDreamWorld.luau")
(ROOT / "tools/InstallModels.luau").write_text(models_only, encoding="utf-8")
print("Generated tools/InstallDreamValley.luau and tools/InstallModels.luau")
