"""Generate the exploration installer from UTF-8 source files."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def read(path):
    return (ROOT/path).read_text(encoding="utf-8-sig")
def literal(text):
    eq="="
    while "]"+eq+"]" in text:
        eq+="="
    return "["+eq+"[\n"+text+"]"+eq+"]"
output=['''-- Generated by tools/GenerateExplorationInstaller.py. Run in EDIT mode.
local RS=game:GetService("ReplicatedStorage")
local package=RS:FindFirstChild("PaperFlight") or Instance.new("Folder")
package.Name="PaperFlight";package.Parent=RS
local remote=package:FindFirstChild("RaceEvent") or Instance.new("RemoteEvent")
remote.Name="RaceEvent";remote.Parent=package
local function write(parent,name,class,source)
 local instance=parent:FindFirstChild(name)
 if instance and class=="ModuleScript" then instance:Destroy();instance=nil end
 instance=instance or Instance.new(class)
 instance.Name=name;instance.Source=source;instance.Parent=parent
end
''']
for parent,name,cls,path in [
 ("package","Config","ModuleScript","src/shared/Config.luau"),
 ("package","Flight","ModuleScript","src/shared/Flight.luau"),
 ("package","FlightCamera","ModuleScript","src/shared/FlightCamera.luau"),
 ("package","Landscape","ModuleScript","src/shared/Landscape.luau"),
 ("package","WorldData","ModuleScript","src/shared/WorldData.luau"),
 ("package","ReferenceAnimals","ModuleScript","src/shared/ReferenceAnimals.luau"),
 ("package","Scenery","ModuleScript","src/shared/Scenery.luau"),
 ("package","MeadowGrass","ModuleScript","src/shared/MeadowGrass.luau"),
 ("package","Economy","ModuleScript","src/shared/Economy.luau"),
 ('game.ServerScriptService',"PaperFlightProfiles","ModuleScript","src/server/ProfileStore.luau"),
 ('game.ServerScriptService',"PaperFlightServer","Script","src/server/RaceServer.server.luau"),
 ('game.StarterPlayer.StarterPlayerScripts',"PaperFlightClient","LocalScript","src/client/FlightClient.client.luau"),
 ('game.StarterPlayer.StarterPlayerScripts',"PaperMeadowGrass","LocalScript","src/client/MeadowGrass.client.luau"),
]:
    output.append(f'write({parent},"{name}","{cls}",{literal(read(path))})\n')
output.append("if not package:FindFirstChild('Plane') then\nlocal function originalArt()\n"+read("tools/BuildDreamWorld.luau")+"\nend\noriginalArt()\nend\n")
output.append("local function planeModels()\n"+read("tools/BuildPlaneModels.luau")+"\nend\nprint(planeModels())\n")
output.append("local function exploration()\n"+read("tools/BuildExplorationWorld.luau")+"\nend\nprint(exploration())\n")
(ROOT/"tools/InstallStudio.luau").write_text("".join(output),encoding="utf-8")
print("Generated exploration tools/InstallStudio.luau")
